### ISSUE TITLE
Error with spamming RetrospectiveCard cooldown

### ISSUE THREAD

**Issue by dellise26** [TRCStudioDean/LiteSignIn#1]
Hello, firstly i should said i love your plugin, really better than a few, simple and automatic, really great.
So yes i came here cause i got some error spamming in the console, then after making a few test, i manage to find the error.
When you take the RetrospectiveCard option on, and have a cooldown, if a player click on a date, it show an error with the time left until the next use for a retrospectiveCard.
Hope you got this soon, and good work
Dellise
![error](https://user-images.githubusercontent.com/38770349/87861913-2ba22c00-c94b-11ea-9c21-66be58929dd2.png)

**Comment by TRCRedstoner** [comment]
Sorry, I only noticed the issues you submitted now. I don’t know if this bug is fixed in the new version. If you are willing to try, you can try to update to the latest version for testing. If the problem still exists, please come again tell me, I am willing to fix these bugs for you.
