### ISSUE TITLE
1.12.2 Join-Event Message Not Working

### ISSUE THREAD

**Issue by TeQTabanca** [TRCStudioDean/LiteSignIn#11]
![Join-Event True Auto-SignIn False](https://user-images.githubusercontent.com/89253304/147871484-49249c93-7526-4525-bcc6-89e70adb4fb2.png)

![Server Join](https://user-images.githubusercontent.com/89253304/147871229-b4b80da6-903d-4845-9080-7dbfce4149cd.png)

### **------------------------------------------------------------------------------------------------------------------------**

![Join-Event True Auto-SignIn True](https://user-images.githubusercontent.com/89253304/147871500-800e89c6-53fe-4521-8731-642a52854644.png)

![Server Join 2](https://user-images.githubusercontent.com/89253304/147871529-86ee66a0-dc41-438b-83ae-26dc441be9fb.png)

**Comment by TRCStudioDean** [comment]
Can you give me your console logs? or find out where there is an error report and send me a screenshot

**Comment by TeQTabanca** [comment]
Server Log:
[2022-01-02-Server-Log.zip](https://github.com/TRCStudioDean/LiteSignIn/files/7813218/2022-01-02-Server-Log.zip)
