### ISSUE TITLE
LiteSignIn

### ISSUE THREAD

**Issue by shiqutong** [TRCStudioDean/LiteSignIn#14]
[15:02:52 INFO]: 签到 >>> 数据库数据保存失败， 发生错误: The last packet success
fully received from the server was 15,067,241 milliseconds ago. The last packet
sent successfully to the server was 15,067,242 milliseconds ago. is longer than
the server configured value of 'wait_timeout'. You should consider either expiri
ng and/or testing connection validity before use in your application, increasing
 the server configured values for client timeouts, or using the Connector/J conn
ection property 'autoReconnect=true' to avoid this problem.
[15:02:52 INFO]: 签到 >>> 成功修复 MySQL 服务器的连接.

**Comment by TRCStudioDean** [comment]
这个报错不影响使用，目前暂时没时间修（请等待数据库引擎代码重写），嫌烦可以在Config.yml的数据库链接参数末尾加上"&autoReconnect=true"
