### ISSUE TITLE
Player clicked and not getting reward

### ISSUE THREAD

**Issue by waiching514** [TRCStudioDean/LiteSignIn#16]
Minecraft Version: 1.16.5
Litesignin Version: 1.6.0
When player clicked gui and sign getting errror on console:
[15:06:28] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LiteSignIn v1.6.0
java.lang.NullPointerException: null
	at studio.trc.bukkit.litesignin.reward.util.SignInTimePeriod.getSetting(SignInTimePeriod.java:13) ~[?:?]
	at studio.trc.bukkit.litesignin.reward.type.SignInSpecialTimePeriodReward.<init>(SignInSpecialTimePeriodReward.java:29) ~[?:?]
	at studio.trc.bukkit.litesignin.database.MySQLStorage.giveReward(MySQLStorage.java:186) ~[?:?]
	at studio.trc.bukkit.litesignin.database.MySQLStorage.signIn(MySQLStorage.java:302) ~[?:?]
	at studio.trc.bukkit.litesignin.event.Menu.click(Menu.java:101) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor763.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by Tollainmear** [comment]
Same to me, btw, can't get player's group by using /signin info.
![image](https://user-images.githubusercontent.com/25898067/166140179-0172ffe1-5adc-4f10-9934-2975131976b3.png)

**Comment by TRCStudioDean** [comment]
> Minecraft Version: 1.16.5 Litesignin Version: 1.6.0 When player clicked gui and sign getting errror on console: [15:06:28] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LiteSignIn v1.6.0 java.lang.NullPointerException: null at studio.trc.bukkit.litesignin.reward.util.SignInTimePeriod.getSetting(SignInTimePeriod.java:13) ~[?:?] at studio.trc.bukkit.litesignin.reward.type.SignInSpecialTimePeriodReward.(SignInSpecialTimePeriodReward.java:29) ~[?:?] at studio.trc.bukkit.litesignin.database.MySQLStorage.giveReward(MySQLStorage.java:186) ~[?:?] at studio.trc.bukkit.litesignin.database.MySQLStorage.signIn(MySQLStorage.java:302) ~[?:?] at studio.trc.bukkit.litesignin.event.Menu.click(Menu.java:101) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor763.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794] at java.lang.Thread.run(Thread.java:829) [?:?]

This is because there is a problem with your own settings, please do as the comments in the file demonstrate.

**Comment by TRCStudioDean** [comment]
> Same to me, btw, can't get player's group by using /signin info. ![image](https://user-images.githubusercontent.com/25898067/166140179-0172ffe1-5adc-4f10-9934-2975131976b3.png)
> 
> Related info:
> 
> * LuckPerms v5.4.18 by Luck.
> * Platform: Bukkit
> * Server Brand: Mohist
> * Server Version: 1.16.5-963 (MC: 1.16.5) - 1.16.5-R0.1-SNAPSHOT

我的建议是不要使用Mohist，这个服务端存在大量未知的无法解决的问题，常常有人和我反馈说GUI点击没反应，但只存在于Mohist，还有各种离奇的Bug，你看这不又来一个

**Comment by Tollainmear** [comment]
soga 了解 辛苦啦

**Comment by TRCStudioDean** [comment]
> 我刚才又试了一下，我这边只要把RewardSettings里的Default加回来就能识别身份组了(只能识别到Default这一层)，所以，我猜测这个Default是不能改的。。。
> 
> 那么问题又来了，我的RewardSetting是按照这样写的：
> 
> ```
> Groups-Priority:
>     - engineer
>     - worker
>     - Default
>     Permission-Groups:
>         #This is the default group, you can't delete it!
>         Default:
>             ....
>         worker:
>             ....
>         engineer:
>             ....
> ```
> 
> 用户的权限组是这样的： ![image](https://user-images.githubusercontent.com/25898067/166294842-f010bd1a-9e1f-4c63-862c-8c92552a11d6.png)
> 
> 请问我应该给LuckPerm的用户组设置什么权限，才能让用户组里的用户自动被LiteSignIn插件识别到对应的奖励组里呢？
> 
> 我曾经尝试过给玩家加与RewordSettings里group同名的权限，也试过把RewordSettings里的group改名成玩家的权限组名，但是都无济于事。

你确定你设置的签到奖励权限节点是正确的吗

**Comment by Tollainmear** [comment]
> > 我刚才又试了一下，我这边只要把RewardSettings里的Default加回来就能识别身份组了(只能识别到Default这一层)，所以，我猜测这个Default是不能改的。。。
> > 那么问题又来了，我的RewardSetting是按照这样写的：
> > ```
> > Groups-Priority:
> >     - engineer
> >     - worker
> >     - Default
> >     Permission-Groups:
> >         #This is the default group, you can't delete it!
> >         Default:
> >             ....
> >         worker:
> >             ....
> >         engineer:
> >             ....
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 用户的权限组是这样的： ![image](https://user-images.githubusercontent.com/25898067/166294842-f010bd1a-9e1f-4c63-862c-8c92552a11d6.png)
> > 请问我应该给LuckPerm的用户组设置什么权限，才能让用户组里的用户自动被LiteSignIn插件识别到对应的奖励组里呢？
> > 我曾经尝试过给玩家加与RewordSettings里group同名的权限，也试过把RewordSettings里的group改名成玩家的权限组名，但是都无济于事。
> 
> 你确定你设置的签到奖励权限节点是正确的吗

果然，我刚才又检查了一遍，才发现之前漏掉了权限的配置方式

```
            #Group permission.
            #When the player has this permission, the parameters of this group will be used.
            #The premise is that you have not mistaken the priority between groups!
            # Permission: signin.reward.worker
            Permission: sign.reward.VIP
```
打扰了

**Comment by waiching514** [comment]
> > Minecraft Version: 1.16.5 Litesignin Version: 1.6.0 When player clicked gui and sign getting errror on console: [15:06:28] [Server thread/ERROR]: Could not pass event InventoryClickEvent to LiteSignIn v1.6.0 java.lang.NullPointerException: null at studio.trc.bukkit.litesignin.reward.util.SignInTimePeriod.getSetting(SignInTimePeriod.java:13) ~[?:?] at studio.trc.bukkit.litesignin.reward.type.SignInSpecialTimePeriodReward.(SignInSpecialTimePeriodReward.java:29) ~[?:?] at studio.trc.bukkit.litesignin.database.MySQLStorage.giveReward(MySQLStorage.java:186) ~[?:?] at studio.trc.bukkit.litesignin.database.MySQLStorage.signIn(MySQLStorage.java:302) ~[?:?] at studio.trc.bukkit.litesignin.event.Menu.click(Menu.java:101) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor763.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-794] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-794] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-794] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2715) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Paper-794] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794] at java.lang.Thread.run(Thread.java:829) [?:?]
> 
> This is because there is a problem with your own settings, please do as the comments in the file demonstrate.
> 
> If you have other questions, please show me the configuration file.

我修复了问题之后, 有时候他们在争取第一的时候会发生这个error, 从而导致无法领取奖励, 通常只有一个人无法领取奖励
https://pastebin.com/m8ctQaGC
