### ISSUE TITLE
当数据库连接错误时玩家可以无限领取奖励

### ISSUE THREAD

**Issue by CuteLittleSky** [TRCStudioDean/LiteSignIn#17]
有时候莫名其妙数据库断了/其他原因 插件连接不上数据库时玩家可以一直点签到领取奖励,数据不会被记录

**Comment by TRCStudioDean** [comment]
我需要你提供日志，或者数据库断连时玩家使用的命令记录截图

**Comment by CuteLittleSky** [comment]
> 我需要你提供日志，或者数据库断连时玩家使用的命令记录截图

https://cowtransfer.com/s/ee64ff8b799e45
