### ISSUE TITLE
返回菜单功能无法使用

### ISSUE THREAD

**Issue by juzijun233** [TRCStudioDean/LiteSignIn#2]
OP权限可以正常返回菜单
但是普通玩家不行
不论是完整的打开命令
还是对应菜单的绑定指令都不行

使用的菜单插件是trmenuv1

**Comment by TRCStudioDean** [comment]
这个和你使用的菜单插件有关系，LSI仅仅是提供了一个执行命令的方法，但它不对执行的命令进行负责，如果你使用的是deluxemenu，你可以将其设置为"server:dm open [菜单] %player_name%"
