### ISSUE TITLE
希望可以選擇是否合併名次（或者新增毫秒判定）

### ISSUE THREAD

**Issue by RICE0707** [TRCStudioDean/LiteSignIn#29]
如題，因為我設定第1、2、3名都有簽到獎勵，
但因為合併名次的關係，幾乎可以說是永遠都給不到第2、3名獎勵，蠻困擾的
![image](https://github.com/TRCStudioDean/LiteSignIn/assets/68499464/4bcb6464-c98c-4bef-abbe-1d9bfb00ece6)

**Comment by TRCStudioDean** [comment]
毫秒判定由于插件的底层逻辑原因无法实现

**Comment by RICE0707** [comment]
> 毫秒判定由于插件的底层逻辑原因无法实现

那麼可以有設定黨選擇是否讓名次合併嗎
