### ISSUE TITLE
续签配置后不生效

### ISSUE THREAD

**Issue by xiaoluofa** [TRCStudioDean/LiteSignIn#31]
![image](https://github.com/TRCStudioDean/LiteSignIn/assets/75927411/3ba54900-4cba-413c-b80e-60bb244b5080)
![image](https://github.com/TRCStudioDean/LiteSignIn/assets/75927411/12e4eebd-7f98-4ac1-bccf-440a5f317a9b)

**Comment by xiaoluofa** [comment]
后台无报错
![image](https://github.com/TRCStudioDean/LiteSignIn/assets/75927411/a9bfd2ec-f1b8-4f3e-ba11-af1131b0fb56)

**Comment by TRCStudioDean** [comment]
你是OP权限但是你改的是Default组的配置

**Comment by xiaoluofa** [comment]
> 你是OP权限但是你改的是Default组的配置

已删除vip组，确实没有用。paper1.20.4挺奇怪的

**Comment by TRCStudioDean** [comment]
哦，我知道是怎么回事了，一会更新一下

**Comment by TRCStudioDean** [comment]
把Retroactive-Times改成Retroactive-Time即可
