### ISSUE TITLE
能否支持自定义GUI和禁止在指定世界签到的功能？

### ISSUE THREAD

**Issue by TATyKeFei** [TRCStudioDean/LiteSignIn#34]
我画了ia贴图，做完发现不能自定义那些物品的位置💦💦💦

**Comment by TRCStudioDean** [comment]
做完了

**Comment by TATyKeFei** [comment]
感谢，自定义 gui 能否添加 CustomModelData 自定义物品?

**Comment by jhqwqmc** [comment]
> 感谢，自定义 gui 能否添加 CustomModelData 自定义物品?

![image](https://github.com/user-attachments/assets/fa755933-f245-4ba1-9d33-2c73c5acf522)
