### ISSUE TITLE
为什么只要我写了GIVE指令就会把我配置文件全部给重置了

### ISSUE THREAD

**Issue by Leoparking** [TRCStudioDean/LiteSignIn#35]
- 'server:minecraft:give @p minecraft:player_head{display:{Name:'{"text":"Train Carriage","color":"gold","underlined":true,"bold":true,"italic":false}',Lore:['{"text":"Custom Head ID: 14871","color":"gray","italic":false}','{"text":"www.minecraft-heads.com","color":"blue","italic":false}']},SkullOwner:{Id:[I;-251977280,1651722947,-1316721151,495860412],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjU4ZDdiMmFlNzgwZTBlMWUwODRlM2VkOTc3MTY5M2RiZDgxOTQzMDM0ZGYxMTVlYzU5NjllNDIyODFlYjUzNSJ9fX0="}]}}} 1'
这样子写？有问题吗？？？
既然是“指令”那不是所有指令都可以用吗？这个指令单独在命令方块里测试是完全没问题的，而且YAML语法也没有问题，把这一行单引号里的指令换成
                    - 'server:eco give {player} 610'
就没事了
真是，youbing

**Comment by TRCStudioDean** [comment]
https://www.bejson.com/validators/yaml_editor/

**Comment by TRCStudioDean** [comment]
即便我收到的邮件里一上来就给我来个 有病吧，我也要提醒你一句，YAML语法中，单引号内的内容若需要包含额外的单引号，需要使用两个单引号进行转义（例如Text: 'What''s your problem?'），这是最基本的YAML语法。

**Comment by TRCStudioDean** [comment]
原
![47176c637a7975bcce9ef921832c26eb](https://github.com/TRCStudioDean/LiteSignIn/assets/50910791/de6d6cf7-8580-452a-aa0b-53066fee9531)
改
![aeb7c3131219d13d6305d7a31d24c74b](https://github.com/TRCStudioDean/LiteSignIn/assets/50910791/634f9374-f781-4d62-bf67-85a8fa7b18cd)

**Comment by Aliorpse** [comment]
> 即便我收到的邮件里一上来就给我来个 有病吧，我也要提醒你一句，YAML语法中，单引号内的内容若需要包含额外的单引号，需要使用两个单引号进行转义（例如Text: 'What''s your problem?'），这是最基本的YAML语法。

太有礼貌了 来看乐子的 还是不打扰了吧（

**Comment by Leoparking** [comment]
> 即便我收到的邮件里一上来就给我来个 有病吧，我也要提醒你一句，YAML语法中，单引号内的内容若需要包含额外的单引号，需要使用两个单引号进行转义（例如Text: 'What''s your problem?'），这是最基本的YAML语法。

**对不起作者**
当时看到我写了这么多然后reload指令后给我重置了，心情非常无语，冲动之下了(我后来觉得不应该这样说就改了)
实在非常抱歉

**Comment by TRCStudioDean** [comment]
热知识，你还可以在同一个文件夹下面找到被重置前的配置文件，格式被改成了.old，而不是被插件删了

**Comment by MinecraftEarthVillage** [comment]
> 热知识，你还可以在同一个文件夹下面找到被重置前的配置文件，格式被改成了.old，而不是被插件删了

刚刚有人发了之前你的聊天记录了，我本来想用吐槽的方式提这个反馈的，发出后感觉不合适，我也立即把标题改了，不过我还是欠你一个道歉
由于在表达意见时没能很好地控制语气，我的措辞可能让您感到不适，这并非我的本意。我深知作为开发者，您付出了很多努力，而我本应以更加尊重和建设性的方式提出问题。。。也……谢谢你给予的帮助，插件很好用，我是支持你的。我也是反对那种开口成脏的、抽象的家伙，遇到好多个，长期接近它们可能也潜移默化影响到我的性情吧😢
![b6024d7adb1282be](https://github.com/user-attachments/assets/52420499-a2eb-46a8-af45-7fcbd9dc0731)
![cdb12db138bcd412](https://github.com/user-attachments/assets/b9a38a60-747b-4283-8903-2b01d91ef9d7)
