### ISSUE TITLE
周期性签到无效

### ISSUE THREAD

**Issue by MinecraftEarthVillage** [TRCStudioDean/LiteSignIn#37]
![image](https://github.com/user-attachments/assets/c57042f8-4384-4367-a8a5-68f9be253c62)
![image](https://github.com/user-attachments/assets/0c2a21cd-4d2d-4277-8966-0eb5c3e7a67c)
![image](https://github.com/user-attachments/assets/be39562f-7d58-4366-96c5-f5f9c694c3b4)

本来是Special-Times-Cycle的变成了Special-Times的奖励了

**Comment by TRCStudioDean** [comment]
RewardSettings.yml发我看看

**Comment by MinecraftEarthVillage** [comment]
> RewardSettings.yml发我看看

[RewardSettings.yml.txt](https://github.com/user-attachments/files/16355669/RewardSettings.yml.txt)
108行-115行

**Comment by TRCStudioDean** [comment]
![image](https://github.com/user-attachments/assets/9d138f8a-a2ec-4b5f-92a6-8a0f5355c3a5)
![image](https://github.com/user-attachments/assets/b464e815-17f0-4a0a-8c82-d78088c1f501)

**然而我的测试结果一切正常**

![image](https://github.com/user-attachments/assets/124b1d36-74be-4818-acb8-3da39e6220bb)
并且，你提供的配置文件有格式错误

**Comment by MinecraftEarthVillage** [comment]
> ![image](https://private-user-images.githubusercontent.com/50910791/352105897-9d138f8a-a2ec-4b5f-92a6-8a0f5355c3a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzk2MzIsIm5iZiI6MTcyMjA3OTMzMiwicGF0aCI6Ii81MDkxMDc5MS8zNTIxMDU4OTctOWQxMzhmOGEtYTJlYy00YjVmLTkyYTYtOGEwZjUzNTVjM2E1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDExMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYmY0YTViNzA3NTk4NGU0ZTFhOTVmYWM4MmM4NmRlOTMzMTk5ZDhjZjhkZTVkZTczZDkzZGU3ZmMzZTI4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1VKCdA7YgOFrp0cBT1WC_VDhOqFv4pv0KvH8OPRyX5Q) ![image](https://private-user-images.githubusercontent.com/50910791/352106017-b464e815-17f0-4a0a-8c82-d78088c1f501.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzk2MzIsIm5iZiI6MTcyMjA3OTMzMiwicGF0aCI6Ii81MDkxMDc5MS8zNTIxMDYwMTctYjQ2NGU4MTUtMTdmMC00YTBhLThjODItZDc4MDg4YzFmNTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDExMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZjA1MDNiNGRhZGJlMmFiMDdkM2E0NGQ2MjNiNjQxMTkyYTA3N2VhMzU1OTJjOTE0ZjZiZjIxMDFjZjg3ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S0WtaQNwEZPliOO00EEw7tI7RcNQg2UB9NDMAtZmDQY)
> 
> **然而我的测试结果一切正常**
> 
> ![image](https://private-user-images.githubusercontent.com/50910791/352106268-124b1d36-74be-4818-acb8-3da39e6220bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNzk2MzIsIm5iZiI6MTcyMjA3OTMzMiwicGF0aCI6Ii81MDkxMDc5MS8zNTIxMDYyNjgtMTI0YjFkMzYtNzRiZS00ODE4LWFjYjgtM2RhMzllNjIyMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI3VDExMjIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMTVmOTI1NjI2M2ZlNzYzMmE3NzMzZDAzMDQ3ZGM3MWM0MjdjMjkwNjc5MzgyMDU5OGEzZTM3ODNiZmE2ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ozHmJpHDdlooxANcEKDuexxwn9EMbYSffgHI96kDEg)并且，你提供的配置文件有格式错误

这就很奇怪了，难道是因为这个自定义物品的原因？
![image](https://github.com/user-attachments/assets/187151d4-70ee-4df5-b8a9-856026791352)
