### ISSUE TITLE
windows Scanned for viruses

### ISSUE THREAD

**Issue by aiaskaHirro** [TRCStudioDean/LiteSignIn#38]
the new plugins visions  [1.8.1.4]  , Window defender  Scanned plugins have  viruses blocked  ,The Reason is this "Trojan:Script/Wacatac.H!ml"   your plugin is that safe ?

**Comment by TRCStudioDean** [comment]
This is a recent issue with the Windows virus library, but less than 1% of people have encountered this situation. You may need to try using some other means to shut it down
