### ISSUE TITLE
[invalid] Date Format

### ISSUE THREAD

**Issue by DaDiGui** [TRCStudioDean/LiteSignIn#4]
I have configured that the date format to view a signature in leaderboard on a specific day is from:
```
    LeaderBoard:
      Date-Format: dd-MM-yyyy

```
When I execute the command: _/signin leaderboard 28-07-2021_ I get the following message in the chat, indicating that the structure is wrong:
The date you specified {date}=28-07-2021 is invalid! Please enter the correct date! (dd-MM-yyyy)

I mean, I'm doing everything right, and it's all set up correctly. However, if I change the position date
_/signin leaderboard 2021-07-28_  Yes, it works and I get the message:
Date 28-07-2021 No one signed in

There must be an error with the date format.

**Comment by TRCStudioDean** [comment]
The option LeadBorad.Date-Format only running at returning messages, but what you said is interesting, I will try to do this at future version.
