### ISSUE TITLE
MySQL 字段太长

### ISSUE THREAD

**Issue by Steve29794** [TRCStudioDean/LiteSignIn#41]
![image](https://github.com/user-attachments/assets/5adf5c37-86fe-446a-bb30-f553546d1d87)
![image](https://github.com/user-attachments/assets/7495dacf-22cb-4ab8-9283-3d1e02c44f9a)
应该考虑建个新表来存储历史，现在已经存不进去了，而且签到排名是第0名

**Comment by TRCStudioDean** [comment]
这是你的MySQL设置问题，而且签到是0名说明你也不是用的最新版本插件，这个bug在一年前就修了

**Comment by Steve29794** [comment]
![image](https://github.com/user-attachments/assets/b457b6ec-8806-440e-b4e6-c8e794440b0d)

**Comment by TRCStudioDean** [comment]
> varchar类型本来就不能存储太长的字符

但是这是longtext

**Comment by TRCStudioDean** [comment]
![image](https://github.com/user-attachments/assets/85005591-ae30-44e8-a3ca-22a44bb40750)

**Comment by Steve29794** [comment]
> > varchar类型本来就不能存储太长的字符
> 
> 但是这是longtext

啊，可是navicat确实显示的varchar，我现在该咋弄

**Comment by TRCStudioDean** [comment]
换MySQL吧，我还真没见过这种情况

**Comment by Steve29794** [comment]
> 换MySQL吧，我还真没见过这种情况

mariadb不行吗

**Comment by TRCStudioDean** [comment]
> > 换MySQL吧，我还真没见过这种情况
> 
> mariadb不行吗

不行，没做这个的兼容

**Comment by Steve29794** [comment]
> > > 换MySQL吧，我还真没见过这种情况
> > 
> > 
> > mariadb不行吗
> 
> 不行，没做这个的兼容

理论上是没问题的 因为mariadb是mysql的分支，我把表删了重启后正常了，是longtext
![image](https://github.com/user-attachments/assets/623cadf9-995c-4851-a032-ebfc4a7fc19e)

**Comment by TRCStudioDean** [comment]
~~把MariaDB看成MongoDB了~~

迁移数据可以使用插件的备份+回档命令实现，旧数据时使用备份，换新数据库后再回档即可

**Comment by Steve29794** [comment]
我草 完蛋了 我已经删了

**Comment by TRCStudioDean** [comment]
![8d2ac64c2d7063a3565851d8d115d1fe](https://github.com/user-attachments/assets/efe5528c-bfc9-49aa-833e-dc13c588feac)
