### ISSUE TITLE
插件SQLite資料轉換至mysql資料庫問題

### ISSUE THREAD

**Issue by TimmyYue** [TRCStudioDean/LiteSignIn#42]
如題，已將插件連接上資料庫後，但是簽到紀錄並不是舊有的而是全新的，有指令或是設定可以將資料轉換至Mysql嗎？並沒有看到相關項目。

**Comment by TRCStudioDean** [comment]
有一种方法，连结回SQLite后，使用/signin database backup进行备份，然后再关闭伺服器切换到MySQL启动后，使用/signin database rollback进行回档即可实现SQLite资料库迁移至MySQL

**Comment by TimmyYue** [comment]
好的，我嘗試看看，謝謝！
