### ISSUE TITLE
signin get error when add custom reward

### ISSUE THREAD

**Issue by Khangb1234** [TRCStudioDean/LiteSignIn#43]
server version: papermc 1.20.4
config file: https://files.catbox.moe/jqpbs5.gz
get error when using command /signin click and click on gui,
error like this: event.buttonclicker()

**Comment by TRCStudioDean** [comment]
![image](https://github.com/user-attachments/assets/71ec4798-f83f-4320-9b0d-71105ef807a8)
If you don't need this type of reward, what you should do is delete it instead of setting it to []
