### ISSUE TITLE
我尝试使用MySQL存储数据，成功连接数据库后不能写入数据

### ISSUE THREAD

**Issue by KaridaLee** [TRCStudioDean/LiteSignIn#46]
![image](https://github.com/user-attachments/assets/456cc0a5-ed66-424d-ba88-ba4e9f5ba9a7)

版本是最新1.8.4.1，Mysql版本是运行在Ubuntu 22 上的5.7.43

**Comment by TRCStudioDean** [comment]
看看show databases;和desc litesignin;

**Comment by KaridaLee** [comment]
![image](https://github.com/user-attachments/assets/3c459616-c7f4-4719-8df4-1e610cda99d7)
我不确定是否正确操作，我是登入LiteSignin需要连接的目标数据库再执行这两条指令的

**Comment by TRCStudioDean** [comment]
看不懂，为什么插件没有自动建库
建议换MySQL 8.0
还不行那就把服务端核心也换一下

**Comment by KaridaLee** [comment]
我尝试在5.7.43版本新建一个空白数据库，再次连接后可以使用了
出错原因也不明，在此前出错的数据库内只有Xconomy的空白数据表
我将关闭这个issue
