### ISSUE TITLE
[invalid] argument {amount}

### ISSUE THREAD

**Issue by DaDiGui** [TRCStudioDean/LiteSignIn#5]
When I type the command: 
_/signin retroactivecard take [amount]_

it seems to me as taken {amount} instead of the written number.
Example: https://i.imgur.com/KAicrPe.png

By executing the Give/Set commands, the number is displayed correctly.

**Comment by TRCStudioDean** [comment]
Hmmm can you give me your messages.yml file?

**Comment by TRCStudioDean** [comment]
No need, I found this problem,  I'm trying to solve it

**Comment by TRCStudioDean** [comment]
This problem has been solved, please wait for the release of version 1.5.4.
