### ISSUE TITLE
[invalid] date order

### ISSUE THREAD

**Issue by DaDiGui** [TRCStudioDean/LiteSignIn#6]
In the gui menu _NextPage_ it seems that it does not detect the month after the current month.
{previousPageMonth}&e-&b{previousPageYear}

https://i.imgur.com/B6YMIul.png

**Comment by TRCStudioDean** [comment]
Your placeholder is incorrect, {previousPage} will display the previous page, and {nextPage} is the next page, which is a different placeholder
