### ISSUE TITLE
打开签到菜单时间过长

### ISSUE THREAD

**Issue by Cnzw** [TRCStudioDean/LiteSignIn#9]
使用mysql数据库

**描述**
在输入 `/signin gui` 时签到菜单过了接近4秒才能显示(服务器内玩家较多)
如果是长时间无人用签到菜单, 则首次使用需要接近13秒才能显示(早上起来赶首个签到这样的玩家)

也许是和数据库长连接有关?

**Comment by TRCStudioDean** [comment]
这个问题其实几个月前就有人反馈了，但是因为我在出差得年末回去所以暂时解决不了

**Comment by Cnzw** [comment]
> 这个问题其实几个月前就有人反馈了，但是因为我在出差得年末回去所以暂时解决不了

对游玩体验的影响比较大，期待你的修复🙏
